name: 'Release notes scrapper'
description: 'Automatically generates release notes for a given release tag, categorized into chapters based on labels.'
inputs:
  tag-name:
    description: 'The tag name of the release to generate notes for.'
    required: true
  chapters:
    description: 'JSON string defining chapters and corresponding labels for categorization.'
    required: true
  warnings:
    description: 'Print warning chapters if true.'
    required: false
    default: 'false'
  published-at:
    description: 'Use `published-at` timestamp instead of `created-at` as the reference point.'
    required: false
    default: 'false'
  skip-label:
    description: 'Skip label used for detection of issues or pull requests to ignore in Release Notes generation process.'
    required: false
    default: 'skip-release-notes'
  print-empty-chapters:
    description: 'Print chapters even if they are empty.'
    required: false
    default: 'true'

branding:
  icon: 'book'
  color: 'yellow'

runs:
  using: 'node20'
  main: 'dist/index.js'
