name: 'Release notes scrapper'
description: 'Automatically generates release notes for a given release tag, categorized into chapters based on labels.'
inputs:
  tag-name:
    description: 'The tag name of the release to generate notes for.'
    required: true
  chapters:
    description: 'JSON string defining chapters and corresponding labels for categorization.'
    required: false
  warnings:
    description: 'Print warning chapters if true.'
    required: false
    default: 'true'
  published-at:
    description: 'Use `published-at` timestamp instead of `created-at` as the reference point.'
    required: false
    default: 'false'
  skip-release-notes-label:
    description: 'Skip label used for detection of issues or pull requests to ignore in Release Notes generation process.'
    required: false
    default: 'skip-release-notes'
  print-empty-chapters:
    description: 'Print chapters even if they are empty.'
    required: false
    default: 'true'
  chapters-to-pr-without-issue:
    description: 'Apply custom chapters for PRs without linked issues.'
    required: false
    default: 'true'
  verbose:
    description: 'Print verbose logs.'
    required: false
    default: 'false'
outputs:
  release-notes:
    description: 'Generated release notes.'
    value: ${{ steps.release-notes-generator.outputs.release-notes }}

branding:
  icon: 'book'
  color: 'yellow'

runs:
  using: 'composite'
  steps:
    - name: Set PROJECT_ROOT and update PYTHONPATH
      run: |
        ACTION_ROOT="${{ github.action_path }}"
        export PYTHONPATH="${PYTHONPATH}:${ACTION_ROOT}/release_notes_generator"
      shell: bash

    - uses: actions/setup-python@v5.1.1
      with:
        python-version: '3.11'
        cache: 'pip'
        cache-dependency-path: ${{ github.action_path }}/**/requirements.txt
#    - run: pip install -r requirements.txt

    #    - name: Install Python dependencies
    #      run: |
    #        pip install -r requirements.txt
    #      shell: bash

    - name: Call Release Notes Generator
      id: release-notes-generator
      env:
        INPUT_GITHUB_TOKEN: ${{ env.GITHUB_TOKEN }}
        INPUT_TAG_NAME: ${{ inputs.tag-name }}
        INPUT_CHAPTERS: ${{ inputs.chapters }}
        INPUT_WARNINGS: ${{ inputs.warnings }}
        INPUT_PUBLISHED_AT: ${{ inputs.published-at }}
        INPUT_SKIP_RELEASE_NOTES_LABEL: ${{ inputs.skip-release-notes-label }}
        INPUT_PRINT_EMPTY_CHAPTERS: ${{ inputs.print-empty-chapters }}
        INPUT_CHAPTERS_TO_PR_WITHOUT_ISSUE: ${{ inputs.chapters-to-pr-without-issue }}
        INPUT_VERBOSE: ${{ inputs.verbose }}
        INPUT_GITHUB_REPOSITORY: ${{ github.repository }}

      run: |
        python ${{ github.action_path }}/main.py
      shell: bash
