name: 'Release notes scrapper'
description: 'Automatically generates release notes for a given release tag, categorized into chapters based on labels.'
inputs:
  tag-name:
    description: 'The tag name of the release to generate notes for.'
    required: true
  chapters:
    description: 'JSON string defining chapters and corresponding labels for categorization.'
    required: false
  warnings:
    description: 'Print warning chapters if true.'
    required: false
    default: 'true'
  published-at:
    description: 'Use `published-at` timestamp instead of `created-at` as the reference point.'
    required: false
    default: 'false'
  skip-release-notes-label:
    description: 'Skip label used for detection of issues or pull requests to ignore in Release Notes generation process.'
    required: false
    default: 'skip-release-notes'
  print-empty-chapters:
    description: 'Print chapters even if they are empty.'
    required: false
    default: 'true'
  chapters-to-pr-without-issue:
    description: 'Apply custom chapters for PRs without linked issues.'
    required: false
    default: 'true'
  verbose:
    description: 'Print verbose logs.'
    required: false
    default: 'false'

branding:
  icon: 'book'
  color: 'yellow'

runs:
  using: 'composite'
  steps:
    - name: Generate release notes
      id: generate-release-notes
      env:
        TAG_NAME: ${{ inputs.tag-name }}
        CHAPTERS: ${{ inputs.chapters }}
        WARNINGS: ${{ inputs.warnings }}
        PUBLISHED_AT: ${{ inputs.published-at }}
        SKIP_RELEASE_NOTES_LABEL: ${{ inputs.skip-release-notes-label }}
        PRINT_EMPTY_CHAPTERS: ${{ inputs.print-empty-chapters }}
        CHAPTERS_TO_PR_WITHOUT_ISSUE: ${{ inputs.chapters-to-pr-without-issue }}

      run: |
        python3 ${{ github.action_path }}/src/release_notes_generator.py
      shell: bash
