name: 'Release notes scrapper'
description: 'Automatically generates release notes for a given release tag, categorized into chapters based on labels.'
inputs:
  tag-name:
    description: 'The tag name of the release to generate notes for.'
    required: true
  chapters:
    description: 'JSON string defining chapters and corresponding labels for categorization.'
    required: true
  warnings:
    description: 'Print warning chapters if true.'
    required: false
    default: 'false'

branding:
  icon: 'book'
  color: 'yellow'

runs:
  using: 'node20'
  main: 'dist/index.js'
