name: Check Release Notes in PR description

on:
  pull_request:
    types: [opened, synchronize, reopened, edited, labeled, unlabeled]
    branches: [ master ]

env:
  SKIP_LABEL: 'no RN'
  RLS_NOTES_TAG_REGEX: 'Release Notes:'

jobs:
  check-release-notes:
    # place your runner here
    runs-on: {your-runner}

    steps:
      - uses: actions/setup-python@83679a892e2d95755f2dac6acb0bfd1e9ac5d548
        with:
          python-version: '3.11'

      - name: Check presence of release notes in PR description
        uses: AbsaOSS/release-notes-presence-check@8e586b26a5e27f899ee8590a5d988fd4780a3dbf
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          github-repository: ${{ github.repository }}
          pr-number: ${{ github.event.number }}
