# .specify/config.yml
specs_dir: specs
outputs:
  constitution: .specify/constitution.md
  plan: .specify/plan.md
  tasks: .specify/tasks/

project:
  name: Release Notes Scrapper
  type: CI Automation
  language: Python
  description: >
    A tool to automate the generation of release notes by scraping commit messages and pull request details from a GitHub repository.
agent:
  mode: brownfield
  focus:
    - CI workflows
    - Release management
    - Automation scripts
