name: Build and Test
on:
  pull_request:
    branches:
      - '**'
    types: [ opened, synchronize, reopened ]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Python dependencies
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install -r requirements.txt
        shell: bash

      - name: Call command python3
        run: python3 --version
        shell: bash

      - name: Set PYTHONPATH environment variable
        run: echo "PYTHONPATH=${GITHUB_WORKSPACE}/src" >> $GITHUB_ENV
        shell: bash

      - name: print PYTHONPATH env variable
        run: echo $PYTHONPATH
        shell: bash

      - name: Build and run unit tests
        run: pytest
